import './css/style.css'

import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import Header from '@/components/ui/header'
import Head from 'next/head'
import Script from 'next/script'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const nacelle = localFont({
  src: [
    {
      path: '../public/fonts/nacelle-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/nacelle-italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/fonts/nacelle-semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/nacelle-semibolditalic.woff2',
      weight: '600',
      style: 'italic',
    },
  ],
  variable: '--font-nacelle',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Script
        src="https://umami.volpionas.synology.me/u.js"
        data-website-id="a43fb404-4a93-4a3b-8523-b493c1e7094c"
        strategy="afterInteractive"
      />

      <html lang="en">
        <body
          className={`${inter.variable} ${nacelle.variable} bg-gray-950 font-inter text-base text-gray-200 antialiased`}
        >
          <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
            <Header />
            {children}
          </div>
        </body>
      </html>
    </>
  )
}
